### PR TITLE
Accessibility improvements for postcards

### PR DESCRIPTION
**Pull request by audie1**
Setting avatar image content description

### CODE REVIEW

**Review by devotaaabel — APPROVED** [review]
Looks good, though I don't think you're merging the semantic tree in this PR

**Comment by audie1** [comment]
Thanks for the reviews @JohnOberhauser and @devotaaabel ... 

I'm going to convert this to a draft for now because I can't get the desired improvements by merging the semantic tree for the postcard composable in PostCard.kt but I'm still tinkering with things. The fact that the postcard is built partially from the HTML of the body text and that's not being merged with my initial attempts seems to be an issue. I'll keep trying a few things and then might need to phone a friend for a resolution if I can't figure it out.

**Comment by devotaaabel** [comment]
@audie1 feel free to remove that bullet point from the description and merge this

**Comment by audie1** [comment]
Ok I'll give it one more try and then I'll remove the bullet point if no luck @devotaaabel

**Comment by audie1** [comment]
Merging this PR, and removing the semantic tree merging point for now, going to revisit that later.

**Pull request merged**
